allowBuilds:
  '@firebase/util': true
  '@google/genai': true
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
minimumReleaseAgeExclude:
  - browserslist@4.29.3
