import { DoorDefinition, ErenSage, MakamItem, WisdomDilemma } from '../models/makam.model';

export const DOORS_DATA: DoorDefinition[] = [
  {
    id: 'seriat',
    name: '1. Şeriat Kapısı',
    symbol: 'Yasa & Sosyal Sözleşme',
    element: 'Hava (Yel)',
    spiritualLevel: 'Hukukî & Zâhirî Seviye',
    modernConcept: 'Hukuk Devleti, Toplumsal Asgari Düzen ve Kamusal Etik',
    description: 'Bireyin topluluk içinde yaşamasını sağlayan asgari normatif zemin. Hak ve hukukun bilinci, sınırların tanınması, ötekinin hakkını gasp etmeme taahhüdü.',
    color: 'text-amber-400',
    accentBg: 'from-amber-500/20 to-amber-900/10',
    borderClass: 'border-amber-500/30',
    icon: 'gavel',
    totalMakams: 10,
  },
  {
    id: 'tarikat',
    name: '2. Tarikat Kapısı',
    symbol: 'Yol & İç Disiplin',
    element: 'Ateş (Od)',
    spiritualLevel: 'Nefs Tezkiyesi & Eylemsel Kararlılık',
    modernConcept: 'Özdenetim, İradî Adanmışlık ve Karakter İnşası',
    description: 'Dışsal yasayı içselleştirme evresi. İnsanın kendi kusurlarıyla yüzleşmesi, bencilliği yakıp kül etmesi ve topluma karşılıksız hizmet etme terbiyesi.',
    color: 'text-rose-400',
    accentBg: 'from-rose-500/20 to-red-950/20',
    borderClass: 'border-rose-500/30',
    icon: 'alt_route',
    totalMakams: 10,
  },
  {
    id: 'marifet',
    name: '3. Marifet Kapısı',
    symbol: 'İrfan & Bilişsel Sezgi',
    element: 'Su (Ab)',
    spiritualLevel: 'Hikmet & Özü Kavrama Mertebesi',
    modernConcept: 'Epistemolojik Derinlik, Bilişsel Olgunluk ve Koşulsuz Şefkat',
    description: 'Kelimelerin ötesindeki öze nüfuz etme. Bilgiyi salt malumat olmaktan çıkarıp içsel bir duyuşa dönüştürme; varlığın gizil ahengini sezme hali.',
    color: 'text-cyan-400',
    accentBg: 'from-cyan-500/20 to-blue-950/20',
    borderClass: 'border-cyan-500/30',
    icon: 'psychology',
    totalMakams: 10,
  },
  {
    id: 'hakikat',
    name: '4. Hakikat Kapısı',
    symbol: 'Bütünleşme & Vahdet',
    element: 'Toprak (Turap)',
    spiritualLevel: 'Fenâ & Kamil İnsan (Varlık Birliği)',
    modernConcept: 'Egosuz Varlık, Kozmik Bütünlük ve Radikal Eşitlik',
    description: 'Özne ile nesne, ben ile öteki arasındaki tüm yapay sınırların çözüldüğü menzil. Tevazu ile toprağa dönmek; 72 millete aynı nazarla bakabilme kemali.',
    color: 'text-emerald-400',
    accentBg: 'from-emerald-500/20 to-teal-950/20',
    borderClass: 'border-emerald-500/30',
    icon: 'all_inclusive',
    totalMakams: 10,
  },
];

export const FORTY_MAKAMS_DATA: MakamItem[] = [
  // ==================== 1. ŞERİAT KAPISI (1 - 10) ====================
  {
    id: 1,
    door: 'seriat',
    numberInDoor: 1,
    title: 'İman ve Güven Sözleşmesi',
    originalTerm: 'İman getirmek',
    classicalMeaning: 'Yaratanın birliğine ve hakikatine kalben tasdik, lisanen ikrar ile teslim olmak.',
    modernInterpretation: 'Evrenin bir ahengi olduğuna, yaşamın tesadüfi bir saçmalıktan ibaret olmadığına duyulan varoluşsal güven.',
    contemporaryPractice: 'Her sabah güne başlarken dünyayla ve insanlıkla barışık bir güven sözleşmesi tazelemek.',
    corePrinciple: 'Temel Ontolojik Güven',
    relatedQuote: 'Hakikate inanmayan, kendi gölgesinden bile korkar.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },
  {
    id: 2,
    door: 'seriat',
    numberInDoor: 2,
    title: 'Öğrenme ve Bilgi Arayışı',
    originalTerm: 'İlim öğrenmek',
    classicalMeaning: 'Farz ve vacip olan dinî ve ahlakî ilimleri tahsil etmek.',
    modernInterpretation: 'Dogmatik kabuller yerine sürekli okuma, sorgulama ve rasyonel bilincini besleme zorunluluğu.',
    contemporaryPractice: 'Cehaletle savaşmak; bilgi kirliliği çağında doğrulanmış hakikatin peşinden gitmek.',
    corePrinciple: 'Epistemik Sorumluluk',
    relatedQuote: 'İlimden gidilmeyen yolun sonu karanlıktır.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },
  {
    id: 3,
    door: 'seriat',
    numberInDoor: 3,
    title: 'İbadet ve Tefekkür Disiplini',
    originalTerm: 'İbadet etmek',
    classicalMeaning: 'Zahiri ibadetleri (namaz, oruç, zikir) vaktinde ve huşu ile eda etmek.',
    modernInterpretation: 'Zihni günlük kaos ve gürültüden arındıran düzenli tefekkür, meditasyon ve şükran pratikleri.',
    contemporaryPractice: 'Günde belirli vakitleri içsel sessizliğe ve ruhsal muhasebeye ayırmak.',
    corePrinciple: 'Düzenli Zihin Arınması',
    relatedQuote: 'Diliyle ibadet eden değil, kalbiyle huzur bulan kurtulur.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 4,
    door: 'seriat',
    numberInDoor: 4,
    title: 'Helal Kazanç ve Alın Teri',
    originalTerm: 'Helal rızık talep etmek',
    classicalMeaning: 'Hile, hırsızlık ve faizden uzak, kendi emeğiyle rızkını temin etmek.',
    modernInterpretation: 'Etik üretim; sömürüye, kul hakkına ve çevre talanına dayanmayan dürüst ekonomi.',
    contemporaryPractice: 'Tükettiğinden fazlasını üretmek; başkasının sırtından geçinmeyi onursuzluk saymak.',
    corePrinciple: 'Ekolojik ve Sosyal Emek Etiği',
    relatedQuote: 'Haram lokma ile beslenen gövdeden hikmet nağmesi çıkmaz.',
    quoteAuthor: 'Ahî Evran-ı Velî',
  },
  {
    id: 5,
    door: 'seriat',
    numberInDoor: 5,
    title: 'Haram ve Şiddetten Uzaklaşma',
    originalTerm: 'Haramdan sakınmak',
    classicalMeaning: 'Hakkın yasak kıldığı günahlardan ve başkasına zarar verecek fiillerden kaçınmak.',
    modernInterpretation: 'Kendi çıkarı için başkasının bedenine, malına ve ruhsal huzuruna kastetmeme ilkesi.',
    contemporaryPractice: 'Dedikodu, karalama, haksız kazanç ve mobbinge karşı tavizsiz durmak.',
    corePrinciple: 'Zarar Vermeme Kuralı (Ahimsa)',
    relatedQuote: 'Eline, diline, beline sahip ol.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },
  {
    id: 6,
    door: 'seriat',
    numberInDoor: 6,
    title: 'Akit ve Sadakat (Nikah/Toplumsal Bağ)',
    originalTerm: 'Nikah kıymak ve akit tutmak',
    classicalMeaning: 'Meşru bir aile bağı kurmak, sözleşmeye ve neslin devamına sadık kalmak.',
    modernInterpretation: 'İlişkilerde şeffaflık, duygusal dürüstlük ve verilen sözlerin arkasında durma erdemi.',
    contemporaryPractice: 'Partnerine, ailesine ve topluma verdiği ahitleri keyfi gerekçelerle bozmamak.',
    corePrinciple: 'İlişkisel Bütünlük',
    relatedQuote: 'Söz ikrardır, ikrarından dönen derviş olamaz.',
    quoteAuthor: 'Pîr Sultan Abdal',
  },
  {
    id: 7,
    door: 'seriat',
    numberInDoor: 7,
    title: 'Liyakat ve Bilgeye Hürmet',
    originalTerm: 'Sünnet ehline hürmet',
    classicalMeaning: 'Peygamberin sünnetine ve salih önderlerin izine saygı göstermek.',
    modernInterpretation: 'Toplumsal hafızayı, emeği geçmiş ustalara hürmeti ve liyakati koruma tavrı.',
    contemporaryPractice: 'Tarihsel birikimi küçümsememek; tecrübeli ve ehil insanlardan danışmanlık almak.',
    corePrinciple: 'Kuşaklararası Saygı ve Liyakat',
    relatedQuote: 'Eski pınarların suyunu taze tutamayan, yeni çeşme açamaz.',
    quoteAuthor: 'Sarı Saltuk',
  },
  {
    id: 8,
    door: 'seriat',
    numberInDoor: 8,
    title: 'Şefkat ve Merhamet Koruması',
    originalTerm: 'Şefkat ve merhamet göstermek',
    classicalMeaning: 'Yetimlere, yoksullara, hayvanlara ve muhtaçlara acıyıp onları gözetmek.',
    modernInterpretation: 'Empati kapasitesini genişletmek; savunmasız canlıların haklarını savunmak.',
    contemporaryPractice: 'Sokak hayvanlarına, kimsesizlere ve mültecilere koşulsuz kucak açmak.',
    corePrinciple: 'Genişletilmiş Empati',
    relatedQuote: 'Dertli olanın derdine derman olmayan, mecliste yer bulamaz.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 9,
    door: 'seriat',
    numberInDoor: 9,
    title: 'Beden ve Çevre Temizliği',
    originalTerm: 'Pâk ve temiz olmak',
    classicalMeaning: 'Bedenî necasetten arınmak, taharet üzere yaşamak.',
    modernInterpretation: 'Fiziksel hijyen, ekolojik temizlik ve yaşam alanlarının estetik intizamı.',
    contemporaryPractice: 'Doğayı kirletmemek; bedenine kimyasal ve toksik yükleme yapmamak.',
    corePrinciple: 'Eko-Beden Sağlığı',
    relatedQuote: 'Dışı pâk olmayanın içi arınmaz.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },
  {
    id: 10,
    door: 'seriat',
    numberInDoor: 10,
    title: 'İyiliği Yayma ve Adaleti Gözetme',
    originalTerm: 'Emr-i bi\'l-maruf ve nehy-i ani\'l-münker',
    classicalMeaning: 'Toplumda adaleti, dürüstlüğü emredip kötülüğü ve zulmü engellemek.',
    modernInterpretation: 'Toplumsal haksızlıklara karşı sessiz kalmama; aktif sivil sorumluluk alma bilinci.',
    contemporaryPractice: 'Zulüm karşısında tarafsız kalmamak; doğruyu cesurca dile getirmek.',
    corePrinciple: 'Etik Yurttaşlık',
    relatedQuote: 'Zulme rıza göstermek zulümdür.',
    quoteAuthor: 'Pîr Sultan Abdal',
  },

  // ==================== 2. TARİKAT KAPISI (11 - 20) ====================
  {
    id: 11,
    door: 'tarikat',
    numberInDoor: 1,
    title: 'Öz Eleştiri ve Dönüşüm (Tövbe)',
    originalTerm: 'Tövbe etmek ve el almak',
    classicalMeaning: 'Geçmiş günahlardan samimi nedamet duyarak bir mürşidin rehberliğinde yola girmek.',
    modernInterpretation: 'Geçmiş hataları rasyonelce kabullenip radikal bir zihinsel format ve dönüşüm başlatmak.',
    contemporaryPractice: 'Bahane üretmeyi bırakıp kendi kusurunu tespit ederek yeni bir hayat sayfası açmak.',
    corePrinciple: 'Radikal Öz-Muhasebe',
    relatedQuote: 'Tevbe kapısı, insanın kendi içine dönüp özüyle barışmasıdır.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },
  {
    id: 12,
    door: 'tarikat',
    numberInDoor: 2,
    title: 'Öğrenci Olma Arzusu (Talep)',
    originalTerm: 'Mürid olmak ve talep etmek',
    classicalMeaning: 'Hakkı arama yolunda heveskar değil, hakiki talip ve öğrenci olmak.',
    modernInterpretation: 'Bilişsel alçakgönüllülük (Intellectual Humility); bilmediğini kabul edip öğrenmeye aç olmak.',
    contemporaryPractice: 'Her gün yeni bir şey öğrenme merakını çocuksu bir saflıkla muhafaza etmek.',
    corePrinciple: 'Sonsuz Öğrenme İştahı',
    relatedQuote: 'Ben bilirim diyenden kaç; bilmediğini bilenin dizinin dibine çök.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 13,
    door: 'tarikat',
    numberInDoor: 3,
    title: 'Sadelik ve Gösterişsizlik (Hırka/Terk)',
    originalTerm: 'Saçını sakalını yol kılmak / hırka giymek',
    classicalMeaning: 'Dünya süsünden ve kibirli makamlardan sıyrılarak sade derviş kisvesine bürünmek.',
    modernInterpretation: 'Minimalizm; statü gösterişinden, tüketim çılgınlığından ve imaj takıntısından özgürleşmek.',
    contemporaryPractice: 'Sadece ihtiyaç duyduğunu tüketmek; kendini sahip olduğu eşyalarla tanımlamamak.',
    corePrinciple: 'İçsel Minimalizm',
    relatedQuote: 'Dervişlik dedikleri hırka ile taç değil; gönlün Hakk ile hemhâl olmasıdır.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 14,
    door: 'tarikat',
    numberInDoor: 4,
    title: 'Nefisle Mücadele (Mücahede)',
    originalTerm: 'Nefisle savaşmak',
    classicalMeaning: 'Bencilliğin, hırsın, şehvetin ve kibrin telkinlerine karşı koymak.',
    modernInterpretation: 'Dürtü kontrolü; anlık hazları erteleyip uzun vadeli erdemli hedeflere odaklanma iradesi.',
    contemporaryPractice: 'Sosyal medya bağımlılığı, öfke patlamaları ve doyumsuzluk krizlerini iradeyle yönetmek.',
    corePrinciple: 'İrade Terbiyesi',
    relatedQuote: 'En büyük cihat, insanın kendi benliğiyle yaptığı savaştır.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },
  {
    id: 15,
    door: 'tarikat',
    numberInDoor: 5,
    title: 'Topluma Hizmet ve Emek (Hizmet)',
    originalTerm: 'Mürşide ve halka hizmet etmek',
    classicalMeaning: 'Dergâhta odun taşımak, sofra kurmak, ayrım yapmaksızın insanlara hizmetkâr olmak.',
    modernInterpretation: 'Kibir kırmanın en yüce yöntemi: Karşılık beklemeden toplum yararına gönüllü çalışmak.',
    contemporaryPractice: 'Derneklerde, aşevlerinde, çevre projelerinde hiçbir unvan talep etmeden ter dökmek.',
    corePrinciple: 'Karşılıksız Hizmetkârlık',
    relatedQuote: 'Kırk yıl dergâha eğri odun taşımadım; bu kapıya eğrinin giremeyeceğini bildim.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 16,
    door: 'tarikat',
    numberInDoor: 6,
    title: 'Vicdani Duyarlılık ve Saygı (Havf)',
    originalTerm: 'Havf (Korku ve incitme endişesi)',
    classicalMeaning: 'Hakkın gazabından ve bir kalbi kırmaktan derin bir endişe duymak.',
    modernInterpretation: 'Korku değil, yüksek nezaket: Başka bir varlığın onurunu zedelemekten titizlikle çekinmek.',
    contemporaryPractice: 'Ağzından çıkan her sözün ve attığın her adımın bir kalp kırmamasına özen göstermek.',
    corePrinciple: 'Hassas Vicdan',
    relatedQuote: 'Bir kez gönül yıktın ise bu kıldığın namaz değil.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 17,
    door: 'tarikat',
    numberInDoor: 7,
    title: 'Geleceğe Güven ve İyimserlik (Reca)',
    originalTerm: 'Reca (Ümit)',
    classicalMeaning: 'Hakkın rahmetinden asla ümit kesmemek.',
    modernInterpretation: 'Zorluklar, travmalar ve krizler karşısında ruhsal dirençlilik (Resilience) ve umut.',
    contemporaryPractice: 'En karanlık toplumsal veya kişisel anlarda dahi pes etmeyip yapıcı eyleme sarılmak.',
    corePrinciple: 'Dirençli Umut',
    relatedQuote: 'Dünle beraber gitti cancağızım, ne kadar söz varsa düne ait; şimdi yeni şeyler söylemek lazım.',
    quoteAuthor: 'Mevlânâ Rûmî & Bektaşî Geleneği',
  },
  {
    id: 18,
    door: 'tarikat',
    numberInDoor: 8,
    title: 'Yol Rehberliği ve Fener Olma (Hidayet)',
    originalTerm: 'Hidayet üzere olmak',
    classicalMeaning: 'Doğru yolun işaretlerine uymak ve başkalarına da örnek bir pusula teşkil etmek.',
    modernInterpretation: 'Tutarlı bir hayat yaşayarak çevresine ilham veren, güvenilir bir mentör olmak.',
    contemporaryPractice: 'Sözleriyle değil, dürüst ve dingin yaşam tarzıyla gençlere yol göstermek.',
    corePrinciple: 'Örnek Teşkil Etme',
    relatedQuote: 'Hünkâr nereye ayak bastıysa orası gülistan oldu.',
    quoteAuthor: 'Sarı Saltuk',
  },
  {
    id: 19,
    door: 'tarikat',
    numberInDoor: 9,
    title: 'Topluluk Ruhu ve Dayanışma (Cemiyet)',
    originalTerm: 'Cemiyet ve sohbet ehli olmak',
    classicalMeaning: 'Cem meclislerinde can cana oturmak, müsahiplik ve kardeşlik hukukunu gözetmek.',
    modernInterpretation: 'Bireycilik krizine karşı kolektif dayanışma, kabileleşmeden açık topluluk kurabilme.',
    contemporaryPractice: 'Haftalık sohbet halkaları, entelektüel buluşmalar ve dost sofraları tertip etmek.',
    corePrinciple: 'Kolektif Bilinç ve Dayanışma',
    relatedQuote: 'Gelin tanış olalım, işi kolay kılalım / Sevelim sevilelim, dünya kimseye kalmaz.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 20,
    door: 'tarikat',
    numberInDoor: 10,
    title: 'Özveri ve Manevi Coşku (Aşk/Şevk)',
    originalTerm: 'Aşk ve vecd hali',
    classicalMeaning: 'Kuru mantığı aşan ilahi muhabbet dalgasına kapılmak.',
    modernInterpretation: 'Yaptığı her işe ruhunu, tutkusunu ve sanatsal coşkusunu katma hali (Flow State).',
    contemporaryPractice: 'İşini, sanatını, ilişkilerini sıradan bir görev gibi değil, adanmış bir aşkla ifa etmek.',
    corePrinciple: 'Tutkulu Adanmışlık',
    relatedQuote: 'Aşksız geçen ömür hederdir; aşktan nasibi olmayan taş gibidir.',
    quoteAuthor: 'Yunus Emre',
  },

  // ==================== 3. MARİFET KAPISI (21 - 30) ====================
  {
    id: 21,
    door: 'marifet',
    numberInDoor: 1,
    title: 'Zarafet ve Edepli Varoluş (Edeb)',
    originalTerm: 'Edeb',
    classicalMeaning: 'Hakkın ve halkın huzurunda haddini bilmek, nefsini terbiye etmek.',
    modernInterpretation: 'Sosyal ilişkilerde incelik, empati, sınır bilinci ve zihinsel nezaket.',
    contemporaryPractice: 'Farklı fikirlere tahammül göstermek, kabalıktan ve dijital linç kültüründen uzak durmak.',
    corePrinciple: 'Varoluşsal Nezaket',
    relatedQuote: 'Girdim ilim meclisine, eyledim talep / Dediler ilim geride, illâ edeb illâ edeb.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 22,
    door: 'marifet',
    numberInDoor: 2,
    title: 'Korkudan Arınmış Huşu (Tazim)',
    originalTerm: 'Korku ve tazim',
    classicalMeaning: 'Cezalandırıcı korku yerine, evrenin haşmetine duyulan derin saygı.',
    modernInterpretation: 'Kozmik huşu (Cosmic Awe); evrenin büyüklüğü karşısında kibrini sıfırlayan hayranlık.',
    contemporaryPractice: 'Yıldızları, dağları, bir yaprağın damarlarını tefekkür ederek kibrini eritmek.',
    corePrinciple: 'Kozmik Hayranlık',
    relatedQuote: 'Korku kölenin işidir, âşıklar hürmetle sever.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },
  {
    id: 23,
    door: 'marifet',
    numberInDoor: 3,
    title: 'Doyumsuzluktan Arınma (Perhiz/Zühd)',
    originalTerm: 'Perhizkarlık',
    classicalMeaning: 'Midesini, gözünü ve kulağını boş ve zararlı şeylerden alıkoymak.',
    modernInterpretation: 'Zihinsel ve bedensel detoks; dijital gürültüden, tüketim iştahından kendini çekebilmek.',
    contemporaryPractice: 'Düzenli ekran orucu tutmak; gereksiz bilgi akışını ve toksik ilişkileri kesmek.',
    corePrinciple: 'Bilişsel Arınma',
    relatedQuote: 'Az ye, az uyu, az söyle; hikmet bunlarda gizlidir.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },
  {
    id: 24,
    door: 'marifet',
    numberInDoor: 4,
    title: 'Metanet ve İçsel Zenginlik (Sabır ve Kanaat)',
    originalTerm: 'Sabır ve kanaat',
    classicalMeaning: 'Musibetlere feryatsız dayanmak ve elindekine gönül hoşluğuyla razı olmak.',
    modernInterpretation: 'Hazza doyumsuzluk çarkından (Hedonic Treadmill) sıyrılıp mevcudun kıymetini bilmek.',
    contemporaryPractice: 'Sürekli daha fazlasını isteme kaygısını terk edip şimdiki anın zenginliğini keşfetmek.',
    corePrinciple: 'Ruhsal Doyum',
    relatedQuote: 'Kanaat tükenmez bir hazinedir; hırs ise doymayan bir cehennemdir.',
    quoteAuthor: 'Ahî Evran-ı Velî',
  },
  {
    id: 25,
    door: 'marifet',
    numberInDoor: 5,
    title: 'İçsel Mahcubiyet ve Saygı (Haya)',
    originalTerm: 'Haya',
    classicalMeaning: 'Gizlide ve açıkta çirkin bir fiil işlemekten kendi vicdanına karşı utanmak.',
    modernInterpretation: 'Başkaları görmese bile kendi vicdan aynasında lekesiz kalabilme ahlakı.',
    contemporaryPractice: 'Kimsenin izlemediği anlarda bile dürüst kalmak; etik gizlilik.',
    corePrinciple: 'Öz-Saygı ve Vicdani İntizam',
    relatedQuote: 'Haya imanın libasıdır; hayası olmayanın insanlığı eksiktir.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },
  {
    id: 26,
    door: 'marifet',
    numberInDoor: 6,
    title: 'Karşılıksız Cömertlik (Seha/İsar)',
    originalTerm: 'Cömertlik (Seha)',
    classicalMeaning: 'Kendi ihtiyacı olsa dahi elindekini başkasına seve seve ikram etmek.',
    modernInterpretation: 'Bolluk zihniyeti (Abundance Mindset); bilgi, zaman ve imkânları cömertçe paylaşmak.',
    contemporaryPractice: 'Öğrendiğin bilgiyi saklamamak, zorda kalan dostuna hesap sormadan el uzatmak.',
    corePrinciple: 'Radikal Paylaşım',
    relatedQuote: 'Veren el alan elden üstündür; paylaştığın senindir, biriktirdiğin değil.',
    quoteAuthor: 'Ahî Evran-ı Velî',
  },
  {
    id: 27,
    door: 'marifet',
    numberInDoor: 7,
    title: 'Sezgisel ve Derin Biliş (İlim/Hikmet)',
    originalTerm: 'İlim ve hakikat bilgisi',
    classicalMeaning: 'Kitapların zahirini aşıp varlığın yaratılış sırrını kavramak.',
    modernInterpretation: 'Sistemik düşünme; hadiselerin ardındaki görünmez neden-sonuç bağlarını analiz edebilme.',
    contemporaryPractice: 'Olaylara yüzeysel değil, tarihsel ve felsefi kökleriyle çok boyutlu bakmak.',
    corePrinciple: 'Bütüncül İdrak',
    relatedQuote: 'İlim ilim bilmektir / İlim kendin bilmektir / Sen kendini bilmezsin / Ya nice okumaktır.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 28,
    door: 'marifet',
    numberInDoor: 8,
    title: 'Tevazu ve İddiasızlık (Miskiniyet)',
    originalTerm: 'Miskiniyet / Mahviyet',
    classicalMeaning: 'Varlık iddiasından soyunup toprak gibi başı eğik olmak.',
    modernInterpretation: 'Ego enflasyonunun panzehiri: Başarılarıyla övünmeyip sıradan bir insan olmanın huzurunu bulmak.',
    contemporaryPractice: 'Övgü aldığında şımarmamak, eleştiri aldığında yıkılmamak; iç dengesini korumak.',
    corePrinciple: 'Sessiz Olgunluk',
    relatedQuote: 'Miskinlikte buldular, kimde erlik var ise / Merdivenden ittiler, yüksekten bakar ise.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 29,
    door: 'marifet',
    numberInDoor: 9,
    title: 'Kalp Gözüyle Tanıma (Marifetullah)',
    originalTerm: 'Marifet',
    classicalMeaning: 'Yaratanı isimleri, sıfatları ve varlıktaki tecellileriyle doğrudan tanımak.',
    modernInterpretation: 'Her varlıkta eşsiz bir değer ve anlam olduğunu kavrayan derin farkındalık.',
    contemporaryPractice: 'İnsanları etnik, dinî veya sosyal etiketleriyle değil, saf insan cevheriyle görmek.',
    corePrinciple: 'Öznel Tanıma Kapasitesi',
    relatedQuote: 'Yetmiş iki milleti bir bilmeyen adam değildir.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },
  {
    id: 30,
    door: 'marifet',
    numberInDoor: 10,
    title: 'Kendi Özünü Tanıma (Kendini Bilmek)',
    originalTerm: 'Kendini bilmek',
    classicalMeaning: '"Nefsini bilen Rabbini bilir" fehvasınca iç alemine ayna tutmak.',
    modernInterpretation: 'Sokratik "Kendini Bil" (Gnothi Seauton) ile tasavvufun birleştiği bilinç sıçraması.',
    contemporaryPractice: 'Korkuların, arzuların ve gölge yanlarınla yüzleşip otantik benliğinle hizalanmak.',
    corePrinciple: 'Aydınlanmış Öz-Farkındalık',
    relatedQuote: 'Her ne arar isen kendinde ara / Kudüs\'te, Mekke\'de, Hac\'da değildir.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },

  // ==================== 4. HAKİKAT KAPISI (31 - 40) ====================
  {
    id: 31,
    door: 'hakikat',
    numberInDoor: 1,
    title: 'Toprak Olmak ve Mutlak Tevazu (Turap)',
    originalTerm: 'Turap olmak',
    classicalMeaning: 'Herkesin bastığı toprak gibi olmak; üzerine basılsa bile çiçek açmak.',
    modernInterpretation: 'Kırılgan egoyu tamamen aşmak; eleştiri veya hakaret karşısında sarsılmayan tabiat gücü.',
    contemporaryPractice: 'Kibirli çıkışlara nezaketle mukabele etmek; toprağın bereketini ruhuna taşımak.',
    corePrinciple: 'Varlıkta Sıfırlanma (Egosuzluk)',
    relatedQuote: 'Toprak gibi mütevazı ol ki, üzerinden bin bir türlü nebat fışkırsın.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },
  {
    id: 32,
    door: 'hakikat',
    numberInDoor: 2,
    title: 'Yetmiş İki Milleti Bir Bilmek',
    originalTerm: 'Yetmiş iki milleti ayıplamamak',
    classicalMeaning: 'Farklı din, ırk ve mezhepten olanları asla kınamamak, hepsini Hakkın tecellisi görmek.',
    modernInterpretation: 'Evrensel İnsan Hakları ve radikal çoğulculuk: Her kültürel ve inançsal kimliğe eşit saygı.',
    contemporaryPractice: 'Ötekileştirici siyaset ve ırkçılık karşısında tavizsiz kapsayıcı ve kucaklayıcı olmak.',
    corePrinciple: 'Kozmopolit Eşitlik',
    relatedQuote: 'Dili, dini, rengi ne olursa olsun; iyiler iyidir.',
    quoteAuthor: 'Hacı Bektâş-ı Velî',
  },
  {
    id: 33,
    door: 'hakikat',
    numberInDoor: 3,
    title: 'Her Şeyden Elini Eteğini Çekip Vermek',
    originalTerm: 'Elinden geleni kimseden esirgememek',
    classicalMeaning: 'Cümle mahlukata faydalı olmak, iyiliği kurumsal ve sürekli bir hale getirmek.',
    modernInterpretation: 'Toplumsal faydayı kişisel servetin önüne koyan vakıf medeniyeti bilinci.',
    contemporaryPractice: 'Sahip olduğun zenginliği miras kavgasına değil, toplumun müşterek refahına adamak.',
    corePrinciple: 'Kolektif Cömertlik',
    relatedQuote: 'Gönül Çalab\'ın tahtı / Çalap gönüle baktı / İki cihan bedbahtı / Kim gönül yıkar ise.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 34,
    door: 'hakikat',
    numberInDoor: 4,
    title: 'Cümle Yaratılmışın Emin Olması',
    originalTerm: 'Cümle yaratılmışın senden emin olması',
    classicalMeaning: 'İnsanın, kurdun, kuşun, ağacın senden asla bir zarar gelmeyeceğini bilmesi.',
    modernInterpretation: 'Radikal ekolojik güvenlik: Biyoçeşitliliğe ve doğaya mutlak dokunulmazlık tanımak.',
    contemporaryPractice: 'Karıncayı bile incitmekten çekinmek; karbon ayak izini ve çevre tahribatını sıfırlamak.',
    corePrinciple: 'Evrensel Güvenilirlik',
    relatedQuote: 'Biz kimseye kin tutmayız / Ağyar dahi dosttur bize.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 35,
    door: 'hakikat',
    numberInDoor: 5,
    title: 'Mülk İddiasından Vazgeçmek',
    originalTerm: 'Mülkü gerçek sahibine teslim etmek',
    classicalMeaning: 'Yeryüzündeki hiçbir şeyin mülkünün insana ait olmadığını idrak etmek.',
    modernInterpretation: 'Emanetçi bilinci: Dünya kaynaklarının geçici bir kullanıcısı olduğunu kavramak.',
    contemporaryPractice: 'Mülkiyet hırsından arınmak; doğayı tüketim nesnesi değil, kutsal bir emanet bilmek.',
    corePrinciple: 'Mülkiyetsizlik Özgürlüğü',
    relatedQuote: 'Mal sahibi mülk sahibi / Hani bunun ilk sahibi / Mal da yalan mülk de yalan / Var biraz da sen oyalan.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 36,
    door: 'hakikat',
    numberInDoor: 6,
    title: 'Sohbette Hakikati Söylemek',
    originalTerm: 'Sohbette sırrı ve hakikati beyan etmek',
    classicalMeaning: 'İkiyüzlülük ve dalkavukluktan uzak, sırf hak olan sözü konuşmak.',
    modernInterpretation: 'Korkusuz ifade özgürlüğü (Parrhesia); baskı altında dahi doğruyu eğip bükmeden savunmak.',
    contemporaryPractice: 'Güç sahiplerine yaranmak için gerçekleri çarpıtmamak; hakikate sadık kalmak.',
    corePrinciple: 'Korkusuz Dürüstlük',
    relatedQuote: 'Dönen dönsün ben dönmezem yolumdan.',
    quoteAuthor: 'Pîr Sultan Abdal',
  },
  {
    id: 37,
    door: 'hakikat',
    numberInDoor: 7,
    title: 'Seyr-i Sülûk (Bilinçli Yolculuk)',
    originalTerm: 'Seyr-i sülûk',
    classicalMeaning: 'Ruhun kesafetten letafete, maddeden manaya doğru durmaksızın yükselişi.',
    modernInterpretation: 'Sürekli kendini aşma (Self-Transcendence); bireyin hiçbir basamakta donup kalmaması.',
    contemporaryPractice: 'Dün ulaştığın manevi ve entelektüel seviyeyi bir dogma haline getirmeyip ilerlemek.',
    corePrinciple: 'Dinamik Tekâmül',
    relatedQuote: 'Her dem yeniden doğarız / Bizden kim usanası.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 38,
    door: 'hakikat',
    numberInDoor: 8,
    title: 'Sırrı Saklamak ve Derinlik (Ketm)',
    originalTerm: 'Sırrı faş etmemek',
    classicalMeaning: 'Ham ervaha ve ehil olmayana hakikatin ağır sırlarını uluorta saçmamak.',
    modernInterpretation: 'Bilişsel olgunluk ve mahremiyet: Her hakikatin bir zamanı, zemini ve muhatabı olduğunu bilmek.',
    contemporaryPractice: 'Sırları ifşa etmemek; derin felsefi meseleleri magazinleştirmeden vakarla korumak.',
    corePrinciple: 'Hikmet Mahremiyeti',
    relatedQuote: 'Sözü bilen kişinin yüzünü ak ede bir söz / Sözü pişirip diyenin işini sağ ede bir söz.',
    quoteAuthor: 'Yunus Emre',
  },
  {
    id: 39,
    door: 'hakikat',
    numberInDoor: 9,
    title: 'Münacat ve Kozmik Bağlantı',
    originalTerm: 'Münacat',
    classicalMeaning: 'Kulu ile yaratan arasında aracısız, perdeler arkasından samimi fısıldaşma.',
    modernInterpretation: 'Evrenin kalbiyle kurulan aracısız içsel irtibat; kurumsal din bezirgânlığına ihtiyaç duymama.',
    contemporaryPractice: 'Gönül tapınağında Hakikat ile aracısız yüz yüze konuşmak.',
    corePrinciple: 'Doğrudan Öz-Temas',
    relatedQuote: 'Kılavuzsuz varılmaz o dergâha; amma dergâh senin kendi gönlündedir.',
    quoteAuthor: 'Abdal Musa',
  },
  {
    id: 40,
    door: 'hakikat',
    numberInDoor: 10,
    title: 'Müşahede ve Birlik (Vahdet/Fenâfillah)',
    originalTerm: 'Müşahede (Hakkı her zerrede görmek)',
    classicalMeaning: 'Gözün gördüğü her surette Hakkın cemâlini seyretmek; ikiliği kökten kaldırmak.',
    modernInterpretation: 'Kozmik Bütünlük Hali (Oceanic Feeling / Non-Dualism); varoluşla bir olma zirvesi.',
    contemporaryPractice: 'Bütün kainatı tek bir nefes gibi hissetmek; öteki diye bir şeyin kalmadığı mutlak barış.',
    corePrinciple: 'Vahdet (Kozmik Birlik)',
    relatedQuote: 'Ete kemiğe büründüm / Yunus diye göründüm.',
    quoteAuthor: 'Yunus Emre',
  },
];

export const ERENLER_DATA: ErenSage[] = [
  {
    id: 'haci-bektas-veli',
    name: 'Hacı Bektâş-ı Velî',
    title: 'Anadolu Mayasının Kurucusu & Pîr-i Horasan',
    era: '13. Yüzyıl (1209 - 1271)',
    location: 'Nişabur / Horasan -> Sulucakarahöyük (Hacıbektaş, Nevşehir)',
    archetype: 'Radikal Hümanist, Akıl ve Ahlak Mimarı',
    modernCounterpart: 'Jürgen Habermas (İletişimsel Akıl) & Baruch Spinoza (Etika ve Doğa Özdeşliği)',
    biography: 'Moğol istilasının Anadolu\'yu yangın yerine çevirdiği bir çağda, Sulucakarahöyük\'te kurduğu dergâh ile kadın ve erkeği eşit kılan, aklı ve ahlakı merkeze alan, 72 millete aynı nazarla bakan eşsiz bir düşünce nizamı inşa etmiştir.',
    philosophicalEssence: 'Evrenin merkezine göksel soyutlamaları değil, doğrudan insanı (mikrokozmosu) yerleştirmiştir. "Hararet nardadır sacda değildir / Keramet baştadır tacda değildir" mısraları, skolastik dogmatizmin tabutuna çakılmış en parlak akılcı çividir.',
    avatarSeed: 'haci_bektas',
    bannerImage: '/assets/default-article-cover.svg',
    bannerCaption: 'Sulucakarahöyük ve Makâlât Tefekkürü • Dört Kapı Kırk Makamın Mimarı',
    symbolicElement: 'Ceylan ile Aslanı Bir Arada Tutan Barış Güvercini',
    keyDifferentiator: 'Bugün kutuplaşan, savaşlarla ve önyargılarla parçalanan dünyada; kadın-erkek eşitliğini 13. yüzyılda "Kadıncık Ana" şahsında kurumsallaştıran, "Eline diline beline sahip ol" formülüyle kusursuz bir yurttaşlık etiği sunan ilk felsefi rehberdir.',
    famousAphorisms: [
      {
        quote: 'Hararet nardadır, sacda değildir / Keramet baştadır, tacda değildir / Her ne arar isen kendinde ara / Kudüs\'te, Mekke\'de, Hac\'da değildir.',
        source: 'Makâlât & Vilâyetnâme',
        modernTake: 'Hakikat dışarıdaki ritüellerde değil; insanın kendi içsel dürüstlüğünde ve ahlakında tecelli eder.',
      },
      {
        quote: 'Kadınları okutunuz; kadını okumayan millet yükselemez.',
        source: 'Öğütler',
        modernTake: '13. yüzyılda cinsiyet eşitliğini ve aydınlanmayı toplumsal kurtuluşun anahtarı gören vizyon.',
      },
      {
        quote: 'İncinsen de incitme.',
        source: 'Makâlât',
        modernTake: 'Şiddet döngüsünü kıran, intikamı değil affı ve erdemi yücelten kategorik ahlak buyruğu.',
      },
    ],
    relatedMakams: [2, 5, 29, 30, 31, 32],
    relatedArticleSlug: 'haci-bektas-i-veli-makalat-dort-kapi-kirk-makam-ontolojisi',
  },
  {
    id: 'yunus-emre',
    name: 'Yunus Emre',
    title: 'Türkçenin Vicdanı & Aşkın Dervişi',
    era: '13. - 14. Yüzyıl (1238 - 1328)',
    location: 'Sarıköy / Eskişehir, Sakarya Havzası',
    archetype: 'Varoluşsal Fenomenolog & Saf Şiirin Pîri',
    modernCounterpart: 'Martin Heidegger (Dasein ve Varlık) & Jean-Paul Sartre (Varoluş Özden Önce Gelir)',
    biography: 'Tapduk Emre\'nin dergâhında kırk yıl nefis terbiyesi gören Yunus, saray ve medresenin Farsça ve Arapçaya teslim olduğu bir devirde, sokaktaki köylünün konuştuğu Türkçeyi felsefenin ve metafiziğin en berrak ırmağı kılmıştır.',
    philosophicalEssence: 'İnsanın kendi içindeki ikiliği ("Bir ben vardır bende benden içeri") keşfetmiş, ten ile can, ego ile hakiki öz arasındaki ontolojik ayrımı çözmüştür. Aşkı romantik bir avuntu değil, evrenin dokusunu birbirine tutturan kozmik çekim kuvveti olarak yorumlamıştır.',
    avatarSeed: 'yunus_emre',
    bannerImage: '/assets/default-article-cover.svg',
    bannerCaption: 'Sakarya Irmağı Kıyısında Türkçe Tefekkür • Duru Dilin Ebedi Sadâsı',
    symbolicElement: 'Dergâha Taşınan Düzgün Odun ve Açan Sarı Çiçek',
    keyDifferentiator: 'Modern insanın "varoluşsal yalnızlığı" ve "anlamsızlık krizine" karşı; dili yalınlaştırarak doğrudan ruha dokunan, insanı doğayla ve diğer canlılarla ("Yaratılanı severiz Yaratan\'dan ötürü") barıştıran en duru terapisttir.',
    famousAphorisms: [
      {
        quote: 'Ete kemiğe büründüm / Yunus diye göründüm.',
        source: 'Divan-ı Yunus',
        modernTake: 'Bedenlenme (embodiment) ve bilincin dünyada geçici bir form alması; varlığın zamandaki tezahürü.',
      },
      {
        quote: 'Beni bende demen bende değilim / Bir ben vardır bende benden içeri.',
        source: 'Divan-ı Yunus',
        modernTake: 'Görünen egonun altında yatan aşkın ve hakiki özün (transandantal özne) keşfi.',
      },
      {
        quote: 'Sevelim sevilelim / Dünya kimseye kalmaz.',
        source: 'Divan-ı Yunus',
        modernTake: 'Ölümlülüğün farkındalığıyla (memento mori) kibri bırakıp dayanışma ve sevgiyi seçme çağrısı.',
      },
    ],
    relatedMakams: [3, 13, 15, 20, 27, 40],
    relatedArticleSlug: 'yunus-emre-siirinde-oz-varlik-ve-turkce-felsefe',
  },
  {
    id: 'pir-sultan-abdal',
    name: 'Pîr Sultan Abdal',
    title: 'Adaletin Ozanı & Politik Vicdanın Sözcüsü',
    era: '16. Yüzyıl (1480 - 1550)',
    location: 'Banaz / Sivas, Yıldızeli',
    archetype: 'Tavizsiz Etik Duruş & Ezilenlerin Sesi',
    modernCounterpart: 'Sokrates (İlkeler Uğruna Baldıran İçen Bilge) & Albert Camus (Başkaldıran İnsan)',
    biography: 'Sivas Banaz yaylasında sazıyla ve deyişleriyle halkın derdini terennüm eden Pîr Sultan, haksız vergilere, rüşvete ve zulme boyun eğmemiş; Hızır Paşa\'nın dünyalık vaatlerine rağmen inandığı yoldan dönmeyerek asılmayı göze almıştır.',
    philosophicalEssence: 'Felsefenin salt fildişi kulelerde soyut kavram üretmek değil, canı pahasına adaletin ve ezilenlerin yanında saf tutmak olduğunu göstermiştir. Şiirlerinde "Yol" bir tarikat adından ziyade evrensel adalet ve vicdan andlaşmasıdır.',
    avatarSeed: 'pir_sultan',
    bannerImage: '/assets/default-article-cover.svg',
    bannerCaption: 'Yıldız Dağı ve Banaz Yaylası • Hakikat Uğruna Baş Eğmeyen Ozan',
    symbolicElement: 'Üç Telli Bağlama ve Kan Kırmızı Dost Gülü',
    keyDifferentiator: 'Konformizmin, ilkesizliğin ve güç karşısında eğilmenin normalleştiği günümüzde; "Dönen dönsün ben dönmezem yolumdan" diyerek vicdani sadakatin ölümsüz manifestosunu sunar.',
    famousAphorisms: [
      {
        quote: 'Koyun beni hak aşkına yanayım / Dönen dönsün ben dönmezem yolumdan.',
        source: 'Pîr Sultan Deyişleri',
        modernTake: 'Dış şartlar ve iktidar baskıları ne olursa olsun, doğru bildiği ahlakî ilkelerden ödün vermemek.',
      },
      {
        quote: 'Şu ellerin taşı hiç bana değmez / İlle dostun bir tek gülü yaralar beni.',
        source: 'Pîr Sultan Deyişleri',
        modernTake: 'Düşmanın açık saldırısı değil; aynı değerleri paylaştığın yol arkadaşının sessizliği ve ihaneti acıtır.',
      },
      {
        quote: 'Bozuk düzende sağlam çark olmaz.',
        source: 'Deyişler',
        modernTake: 'Yapısal adaletsizliğin hüküm sürdüğü bir sistemde, bireysel dürüstlüklerin yetersiz kalacağına dair sosyolojik teşhis.',
      },
    ],
    relatedMakams: [6, 10, 36],
    relatedArticleSlug: 'pir-sultan-abdal-poetikasinda-direnis-ve-politik-ontoloji',
  },
  {
    id: 'sari-saltuk',
    name: 'Sarı Saltuk Baba',
    title: 'Balkanlar\'ın Barış Mimarı & Sınır Aşan Derviş',
    era: '13. Yüzyıl (1200 - 1298)',
    location: 'Sinop -> Dobruca (Babadağ, Romanya) -> Kruja / Ohri / Kırım',
    archetype: 'Kültürlerarası Arabulucu & Barış Elçisi (Kolonizatör Derviş)',
    modernCounterpart: 'Hans-Georg Gadamer (Ufukların Kaynaşması) & Emmanuel Levinas (Ötekinin Sonsuz Sorumluluğu)',
    biography: 'Hacı Bektâş-ı Velî\'nin himmeti ve talimatıyla Anadolu\'dan Balkanlar\'a geçen Sarı Saltuk, kılıçla fethetmek yerine sevgiyle, aşeviyle, adaletle ve ortak kültürel sembollerle Hristiyan ve Müslüman halkların gönlünde taht kurmuştur. Dobruca\'dan Ohri\'ye, Bosna\'dan Arnavutluk\'a kadar Balkanlar\'da onlarca makamı (türbesi) vardır ve hem Hristiyanlar (Aziz Naum / Aziz Corc adıyla) hem Müslümanlar tarafından asırlardır hürmetle ziyaret edilir.',
    philosophicalEssence: 'Kimliklerin çatışmacı değil, geçirgen ve kucaklayıcı olabileceğini fiilen kanıtlamıştır. Farklı inançların kutsallarını yıkmak yerine, ortak adalet ve insanlık zemininde kaynaştıran "kültürlerarası hermeneutik" dehasıdır.',
    avatarSeed: 'sari_saltuk',
    bannerImage: '/assets/default-article-cover.svg',
    bannerCaption: 'Balkan Dağları ve Dobruca Ovası • Medeniyetleri Birleştiren Eren',
    symbolicElement: 'Ahşap Tahta Kılıç ve Ejderhayı Terbiye Eden Asa',
    keyDifferentiator: 'Balkanlar\'da ve Doğu Avrupa\'da çok-kültürlülüğün, hoşgörünün ve birlikte yaşama kültürünün öncüsüdür. Tahta kılıcı, kan dökmeyen manevi irfanı simgeler.',
    famousAphorisms: [
      {
        quote: 'Kılıcımız çelikten değil, tahtadandır; çünkü biz can almaya değil, can vermeye geldik.',
        source: 'Saltuknâme (Ebu\'l-Hayr Rûmî)',
        modernTake: 'Şiddetsizlik ilkesi: Gerçek fetih toprak kazanmak değil, insanın kalbini adalet ve merhametle kazanmaktır.',
      },
      {
        quote: 'Yabancıya evini açmayan, kendi memleketinde de gariptir.',
        source: 'Saltuknâme Rivayetleri',
        modernTake: 'Mültecilere ve yabancılara gösterilen konukseverliğin uygarlığın gerçek ölçüsü olduğu bilinci.',
      },
      {
        quote: 'Bir nehrin iki yakasındaki köylüler birbirine düşman ise, o nehir bereket değil kan taşır.',
        source: 'Balkan Menâkıbı',
        modernTake: 'Sınırları ve nehirleri ayrıştırıcı değil, birleştirici bir barış koridoru kılma ideali.',
      },
    ],
    relatedMakams: [7, 8, 18, 32, 34],
    relatedArticleSlug: 'sari-saltukun-balkanlardaki-baris-misyonu-ve-kulturlerarasi-irfan',
  },
  {
    id: 'ahi-evran',
    name: 'Ahî Evran-ı Velî',
    title: 'Üretim Ahlakının ve Dayanışmanın Kurucusu',
    era: '13. Yüzyıl (1169 - 1261)',
    location: 'Hoy / Azerbaycan -> Kayseri, Kırşehir, Konya',
    archetype: 'İktisat Filozofu & Meslek Ahlakı Mimarı',
    modernCounterpart: 'Amartya Sen (Etik ve İktisat) & E.F. Schumacher (Küçük Güzeldir)',
    biography: 'Kırşehir\'de kurduğu Ahilik Teşkilatı ile esnafı, sanatkârları ve tüccarları "Akıl, Ahlak, Adalet ve Çalışma" dörtgeninde birleştirmiştir. Eşi Fatma Bacı ise dünyanın ilk kadın teşkilatlanması sayılan "Bâcıyân-ı Rûm" (Anadolu Kadınları Birliği)\'u kurmuştur.',
    philosophicalEssence: 'Ekonomiyi vahşi kâr hırsından arındırıp ahlakî bir hizmete dönüştürmüştür. "Pabucu dama atılmak" deyimi Ahilik denetiminden doğmuştur; kusurlu mal üreten esnafın pabucu dama atılarak meslekten men edilirdi.',
    avatarSeed: 'ahi_evran',
    bannerImage: '/assets/default-article-cover.svg',
    bannerCaption: 'Kırşehir Ahi Ocağı • Emeğin, Sanatın ve Fütüvvetin Merkezi',
    symbolicElement: 'Deri Tabaklama Taşı ve Fütüvvet Kuşağı',
    keyDifferentiator: 'Bugünün vahşi kapitalizmine, tüketim çılgınlığına ve güvencesiz emek sömürüsüne karşı; kooperatifçiliği, kalite kontrolü ve adil gelir dağılımını 800 yıl önce uygulamış en somut iktisat dehasıdır.',
    famousAphorisms: [
      {
        quote: 'Hak ile sabır dileyip bize gelen bizdendir / Akıl ve ahlak ile çalışan bizi geçendir.',
        source: 'Ahi Ocak Düsturu',
        modernTake: 'Çırağın ustasını geçmesini teşvik eden, yenilikçi ve liyakat odaklı zanaat felsefesi.',
      },
      {
        quote: 'Harama bakma, haram yeme, haram içme. Doğru, sabırlı, dayanıklı ol. Yalan söyleme. Büyüklerinden önce söze başlama.',
        source: 'Fütüvvetnâme',
        modernTake: 'İş ahlakı ve profesyonel dürüstlüğün temel kuralları.',
      },
    ],
    relatedMakams: [4, 24, 26],
  },
  {
    id: 'seyyid-nesimi',
    name: 'Seyyid Nesîmî',
    title: 'Hakikat Aşığı & Tavizsiz Hürriyet Şairi',
    era: '14. Yüzyıl (1369 - 1417)',
    location: 'Şamahı / Azerbaycan -> Halep',
    archetype: 'Hakikat Uğruna Canını Veren İrfan Şehidi',
    modernCounterpart: 'Giordano Bruno & Baruch Spinoza',
    biography: 'Azerbaycan ve Anadolu sahasında duru bir Türkçe ve coşkun gazellerle "Enel Hak" (Ben Hakikatim) hakikatini haykıran, Halep\'te bağnaz fukahâ tarafından derisi yüzülerek şehit edilen büyük mutasavvıf.',
    philosophicalEssence: 'İnsanın Tanrısal nurun en kâmil aynası olduğunu savunmuştur. Dışsal şekilperestliğe ve din bezirgânlığına karşı insanın kutsallığını ve onurunu canı pahasına savunmuştur.',
    avatarSeed: 'seyyid_nesimi',
    bannerImage: '/assets/default-article-cover.svg',
    bannerCaption: 'Mekân ile Lâ-Mekân Arasında İrfanî Çözümleme • Nesîmî Divanı',
    symbolicElement: 'Hakikat Divanı ve Yüzülen Deri Sembolü',
    keyDifferentiator: 'Düşünce özgürlüğü uğruna hayatını feda etmenin en trajik ve yüce sembolüdür.',
    famousAphorisms: [
      {
        quote: 'Bende sığar iki cihan ben bu cihana sığmazam / Gevher-i lâ-mekân menem kevn ü mekâna sığmazam.',
        source: 'Nesîmî Divanı',
        modernTake: 'İnsanın bilinci ve manevi potansiyeli evrenden daha geniştir; insan hiçbir dar kalıba hapsedilemez.',
      },
      {
        quote: 'Rızkımı veren Huda\'dır, kula minnet eylemem.',
        source: 'Gazeller',
        modernTake: 'Kimseye boyun eğmeyen, ekonomik ve düşünsel bağımsızlık bilinci.',
      },
    ],
    relatedMakams: [30, 36, 40],
  },
  {
    id: 'abdal-musa',
    name: 'Abdal Musa Sultan',
    title: 'Tekke Kültürünün Kutbu & Kaygusuz\'un Mürşidi',
    era: '14. Yüzyıl',
    location: 'Horasan -> Elmalı, Antalya (Tekke Köyü)',
    archetype: 'Doğayla Bütünleşen Derviş & Alevi-Bektaşi Erkanı',
    modernCounterpart: 'Henry David Thoreau (Doğada Yaşam ve Sivil İtaatsizlik)',
    biography: 'Hacı Bektâş-ı Velî\'nin önde gelen halifelerinden olup Antalya Elmalı\'da kurduğu tekke ile Alanya Beyi\'nin oğlu Gaybi\'yi (Kaygusuz Abdal) yetiştirmiş; dağlarda, yaylalarda arı duru bir yaşam sürmüştür.',
    philosophicalEssence: 'Tasavvufun doğadan kopuk bir soyutlama değil, bizzat toprağın, suyun ve dağın koynunda yaşanan canlı bir tecrübe olduğunu göstermiştir.',
    avatarSeed: 'abdal_musa',
    bannerImage: '/assets/default-article-cover.svg',
    bannerCaption: 'Elmalı Dağları ve Abdal Musa Tekkesi • Doğa ve İrfan Sentezi',
    symbolicElement: 'Geyik Boynuzu ve Asa',
    keyDifferentiator: 'Doğa mistisizmi ve insanın tabiatla barışık yaşaması konusunda benzersiz bir rehberdir.',
    famousAphorisms: [
      {
        quote: 'Gözün gördüğü haktır, gönlün duyduğu aşktır.',
        source: 'Abdal Musa Velâyetnâmesi',
        modernTake: 'Algıladığın evren ile kalbindeki sevgi birleştiğinde gerçek aydınlanma başlar.',
      },
    ],
    relatedMakams: [9, 14, 34],
  },
];

export const WISDOM_DILEMMAS: WisdomDilemma[] = [
  {
    id: 'dilemma-burnout',
    situation: 'Sürekli tükenmişlik hissediyorum, hayat bir koşuşturmaca ve anlamsız geliyor.',
    description: 'Modern hayatın hızlı tüketim döngüsü ve aşırı uyarılma hali ruhsal boşluk yaratır.',
    category: 'zihin',
    door: 'tarikat',
    makamNumber: 13,
    makamTitle: 'Sadelik ve Gösterişsizlik (Hırka/Minimalizm)',
    sageName: 'Yunus Emre',
    sageQuote: 'Dervişlik dedikleri hırka ile taç değil; gönlün Hakk ile hemhâl olmasıdır.',
    actionableStep: 'Bugün tüm bildirimleri 4 saatliğine kapat; gereksiz 3 eşyayı ihtiyacı olan birine hediye et ve yalnızca nefesine odaklan.',
  },
  {
    id: 'dilemma-injustice',
    situation: 'İş yerimde veya toplumda haksızlık görüyorum, sessiz kalmak vicdanımı eziyor.',
    description: 'Güç sahiplerinin haksızlıkları karşısında çaresizlik ve boyun eğme dürtüsü.',
    category: 'vicdan',
    door: 'hakikat',
    makamNumber: 36,
    makamTitle: 'Sohbette Hakikati Söylemek (Parrhesia)',
    sageName: 'Pîr Sultan Abdal',
    sageQuote: 'Dönen dönsün ben dönmezem yolumdan / Yolumdan dönüp mahrum mu kalayım?',
    actionableStep: 'Korkunu kabul et ama haksızlığa ortak olma. Doğruyu nezaketle fakat net bir dille ifade et; omurgalı duruşunu koru.',
  },
  {
    id: 'dilemma-ego',
    situation: 'Eleştirildiğimde çok öfkeleniyorum, gururum inciniyor ve savunmaya geçiyorum.',
    description: 'Kırılgan benlik algısı ve onay bağımlılığının yol açtığı öfke nöbetleri.',
    category: 'varoluş',
    door: 'hakikat',
    makamNumber: 31,
    makamTitle: 'Toprak Olmak ve Mutlak Tevazu (Turap)',
    sageName: 'Hacı Bektâş-ı Velî',
    sageQuote: 'Toprak gibi mütevazı ol ki, üzerinden bin bir türlü nebat fışkırsın. İncinsen de incitme.',
    actionableStep: 'Sana yöneltilen eleştirideki hakikat payını tarafsızca ayıkla. Savunma yapmadan önce 3 derin nefes al ve öfkenin geçmesini bekle.',
  },
  {
    id: 'dilemma-polarization',
    situation: 'Farklı görüşteki insanlara tahammül edemiyorum, toplum çok kutuplaştı.',
    description: 'Yankı odalarında (echo-chambers) sıkışma ve ötekini düşmanlaştırma eğilimi.',
    category: 'toplum',
    door: 'hakikat',
    makamNumber: 32,
    makamTitle: 'Yetmiş İki Milleti Bir Bilmek',
    sageName: 'Sarı Saltuk & Hacı Bektâş',
    sageQuote: 'Yetmiş iki milleti bir bilmeyen adam değildir. Dili, dini, rengi ne olursa olsun iyiler iyidir.',
    actionableStep: 'Bugün fikirlerine tamamen zıt olan bir yazarın makalesini empati kurarak oku; önyargını fark edip dinlemeyi dene.',
  },
  {
    id: 'dilemma-greed',
    situation: 'Sürekli daha fazla para ve unvan kazanmak zorundaymışım gibi bir baskı altındayım.',
    description: 'Kapitalist statü anksiyetesi ve başkalarıyla bitmek bilmeyen kıyaslama.',
    category: 'varoluş',
    door: 'marifet',
    makamNumber: 24,
    makamTitle: 'Metanet ve İçsel Zenginlik (Sabır ve Kanaat)',
    sageName: 'Ahî Evran-ı Velî',
    sageQuote: 'Kanaat tükenmez bir hazinedir; hırs ise doymayan bir cehennemdir.',
    actionableStep: 'Bugün satın almayı düşündüğün lüks bir tüketim nesnesinden vazgeç ve o bütçeyi bir öğrenciye burs veya bir fidan bağışına ayır.',
  },
  {
    id: 'dilemma-forgiveness',
    situation: 'Bana haksızlık yapan bir dostumu affedemiyorum, içimdeki kin beni zehirliyor.',
    description: 'Geçmişe takılı kalma ve intikam duygusunun ruhu esir alması.',
    category: 'vicdan',
    door: 'seriat',
    makamNumber: 8,
    makamTitle: 'Şefkat ve Merhamet Koruması',
    sageName: 'Yunus Emre',
    sageQuote: 'Biz kimseye kin tutmayız / Ağyar dahi dosttur bize / Nerede baksak Hakk\'ı görürüz / Cümle cihan birdir bize.',
    actionableStep: 'Affetmek o kişinin yaptığını onaylamak değil; o kişinin senin zihnindeki zehirli kirasını iptal etmektir. Kendi özgürlüğün için affet.',
  },
];
